### ISSUE TITLE
Bug in add and sub for extreme values

### ISSUE THREAD

**Issue by dpsanders** [JeffreySarnoff/FastRounding.jl#11]
```
julia> sub_round(1.7976931348623157e308, -1.7976931348623157e308, RoundDown)
Inf
```
This should give `1.7976931348623157e308`.

This comes from
```
julia> subtract_errorfree(1.7976931348623157e308, -1.7976931348623157e308)
(Inf, NaN)
```
Since `hi` is `Inf`, rounding down should give `prevfloat(Inf)`.

**Comment by JeffreySarnoff** [comment]
presupposing the corner cases were fixed, does this distinction concern you? 

```julia
prevfloat(Inf) == realmax(Float64)
nextfloat(-Inf) == realmin(Float64)
```
```julia
using AdjacentFloats
prev_float(Inf) == Inf
next_float(-Inf) == -Inf
```

**Comment by dpsanders** [comment]
Yes it does! 
Since this is the way to correctly return the interval from typemax(Float64) to Infinity when the answer lies somewhere in between.

**Comment by JeffreySarnoff** [comment]
notice the typo correction `next_float(-Inf) == -Inf)`

Are you saying that there are interval algorithms that you use which expect to step  from the infinite to the finite floats (*not the same as stepping from the finite floats to the infinite*)?  It sounds like you are using Interval( realmax(FP),  (FP)(Inf) ) to mean `huge positive finite value` .. is that correct?

**Comment by dpsanders** [comment]
Yes, exactly. For example, to calculate $2^2000$ we can do
```jl
julia> using IntervalArithmetic

julia> @format full    # give full output
6

julia> a = (2..2)^2000
Interval(1.7976931348623157e308, Inf)
```

This says that the answer is a real number that is bigger than `realmax()`.
The answer `Interval(Inf, Inf)` is incorrect, since the answer is not infinity; it's a finite, but non-representable float. 

This is standard in interval arithmetic.

**Comment by JeffreySarnoff** [comment]
ok, that then

**Comment by JeffreySarnoff** [comment]
When you compute `(2..2)^2000` that becomes `(2^2000 .. 2^2000)` either explicitly or implicitly and, either way, you calculate `2^2000` at least once ... yes? So before your answer is returned as `Interval(1.7e308, Inf)` is `Interval(Inf, Inf)` a checked exceptional case that you translate to `Interval(1.7e308, Inf)` ... or ... does it happen differently?

**Comment by dpsanders** [comment]
For example,
```jl
julia> a = Interval(1e300)
Interval(1.0e300, 1.0e300)

julia> b = Interval(1e9)
Interval(1.0e9, 1.0e9)

julia> a * b
Interval(1.7976931348623157e308, Inf)
```

This effectively calculates
```jl
julia> *(a.lo, b.lo, RoundDown)
1.7976931348623157e308
```
which reduces to
```jl
julia> setrounding(Float64, RoundDown) do
           a.lo * b.lo
       end
1.7976931348623157e308
```
whereas with rounding to nearest we have
```jl
julia> a.lo * b.lo
Inf
```

**Comment by JeffreySarnoff** [comment]
oic

**Comment by JeffreySarnoff** [comment]
I think the new release covers this.

**Comment by JeffreySarnoff** [comment]
closing on that basis
