### ISSUE TITLE
Another extreme bug

### ISSUE THREAD

**Issue by dpsanders** [JeffreySarnoff/FastRounding.jl#12]
```
julia 0.6> FastRounding.add_round(prevfloat(Inf), prevfloat(Inf), RoundDown)
Inf
```
This should give `prevfloat(Inf)`.

**Comment by dpsanders** [comment]
~This is a bug in `ErrorfreeArithmetic`~ This is due to the output of `ErrorfreeArithmetic`:
```
julia 0.6> ErrorfreeArithmetic.add_errorfree(prevfloat(Inf), prevfloat(Inf))
(Inf, NaN)
```

**Comment by dpsanders** [comment]
Seems like this will be a bug whenever the sum is `Inf`.

Found by @sacha0

**Comment by dpsanders** [comment]
The bug is in `FastRounding`, not `ErrorfreeArithmetic`, which gives the correct answer.
All operations in `FastRounding` must check if the result is `Inf` or `-Inf`, and round appropriately.

**Comment by JeffreySarnoff** [comment]
is the only issue with this family of expressions?
```julia
setrounding(Float64, RoundDown) do; prevfloat(Inf) + prevfloat(Inf); end
1.7976931348623157e308
setrounding(Float64, RoundUp) do; nextfloat(-Inf) + nextfloat(-Inf); end
-1.7976931348623157e308
setrounding(Float64, RoundUp) do; nextfloat(-Inf) - prevfloat(Inf); end
-1.7976931348623157e308
# etc
```

**Comment by dpsanders** [comment]
The problem is with any operation that produces an infinity, e.g.
```jl
julia 0.6> add_round(prevfloat(Inf), 1e300, RoundDown)
Inf
```

**Comment by JeffreySarnoff** [comment]
why, rounding down, is prevfloat(Inf) + abs(any finite Float64 >
nextfloat(0.0)) not Inf?

**Comment by dpsanders** [comment]
Because the result (of adding two intervals) must strictly contain any
possible result.

**Comment by Sacha0** [comment]
More generally, for consistency with the IEEE 754 directed rounding modes? (Inferring behavior from experimentation at the REPL, haven't read the specification itself.) Best!
```julia
julia> setrounding(Float64, RoundDown)
0

julia> prevfloat(Inf) + 1.0
1.7976931348623157e308

julia> setrounding(Float64, RoundUp)
0

julia> nextfloat(-Inf) - 1.0
-1.7976931348623157e308
```

**Comment by JeffreySarnoff** [comment]
helpful -- I just want the fix to stay out of the way most of the time
some Benchmarking of alternatives is in order -- will post findings

**Comment by JeffreySarnoff** [comment]
please confirm that this is the logic you seek
```julia
@inline function round_errorfree{T<:SysFloat}(hi::T, lo::T, ::RoundingMode{:Nearest})::T
     !isinf(hi) && return hi
     return signbit(hi) ? T(-Inf) : T(Inf)
end

@inline function round_errorfree{T<:SysFloat}(hi::T, lo::T, ::RoundingMode{:ToZero})::T
     !isinf(hi) && return signbit(hi) != signbit(lo) ? AdjacentFloats.next_nearerto_zero(hi) : hi
     return signbit(hi) ? nextfloat(T(-Inf)) : prevfloat(T(Inf))
end

@inline function round_errorfree{T<:SysFloat}(hi::T, lo::T, ::RoundingMode{:FromZero})::T
    !isinf(hi) && return signbit(hi) == signbit(lo) ? AdjacentFloats.next_awayfrom_zero(hi) : hi
    return signbit(hi) ? T(-Inf) : T(Inf)
end

@inline function round_errorfree{T<:SysFloat}(hi::T, lo::T, ::RoundingMode{:Up})::T
    !isinf(hi) && return (lo<=zero(T) || isnan(lo))  ? hi : next_float(hi)
    return signbit(hi) ? nextfloat(T(-Inf)) : T(Inf)
end

@inline function round_errorfree{T<:SysFloat}(hi::T, lo::T, ::RoundingMode{:Down})::T
    !isinf(hi) && return (lo>=zero(T) || isnan(lo))  ? hi : prev_float(hi)
    return signbit(hi) ? T(-Inf) : prevfloat(T(Inf))
end
```

**Comment by JeffreySarnoff** [comment]
@dpsanders just check that the way infinities are handled matches expectation -- nothing else is altered .. all I am asking is for confirmation that the request and the changes match before introducing this as higher version

**Comment by JeffreySarnoff** [comment]
I assume silence is agreement :-> 
I merged the prior comment's edits and have it as new version

**Comment by JeffreySarnoff** [comment]
I think the new release covers this.

**Comment by JeffreySarnoff** [comment]
closing on that basis

**Comment by dpsanders** [comment]
Sorry for the delay in getting to this. Looking good!
