### ISSUE TITLE
New minor version when remove 0.6 compatibility

### ISSUE THREAD

**Issue by dpsanders** [JeffreySarnoff/FastRounding.jl#18]
Which version removed compatibility with Julia 0.6? It would have been usual to tag a new minor version then.

**Comment by JeffreySarnoff** [comment]
v0.2.0 introduced the Unicode infix ops.  That altered the API, so v0.1.x become v0.2.0. 
That is the only compatibility influence afaik.  I changed the REQUIRE to v0.7 -- but that has not been tagged yet and the only reason I did that was to deal with the flack this am.  Your stuff worked for you without the change to REQUIRE -- so I am more than happy to unchange it.

**Comment by JeffreySarnoff** [comment]
and I would go to v0.2.1 when tagging that as new release -- doing that now??

**Comment by dpsanders** [comment]
The problem is that v0.2 wrongly states that it is compatible with Julia 0.6, so that will be the version that the package manager installs. I think we should try to retroactively change the Julia version on release 0.2 to 0.7.

**Comment by JeffreySarnoff** [comment]
yes -- that was my oversight.  I'm changing the require to reflect that and will add a note on the metadata thread.
