### ISSUE TITLE
sqrt wrong?

### ISSUE THREAD

**Issue by dpsanders** [JeffreySarnoff/FastRounding.jl#20]
You have
```
@inline function sqrt_round(a::T, ::RoundingMode{:Down}) where {T<:SysFloat}
    hi = sqrt(a)

    while hi*hi > a
        hi = prevfloat(hi)
    end

    return hi
end
```

Don't you need to use `mul_round(hi, hi, RoundUp)` instead of just `hi * hi`?

**Comment by JeffreySarnoff** [comment]
IEEE 754-2008

sqrt(NaN, AnyRoundingMode) == NaN
sqrt(Inf, AnyRoundingMode) == Inf
sqrt(0.0, AnyRoundingMode) == 0.0
sqrt(-0.0, AnyRoundingMode) == -0.0
sqrt(x<0, AnyRoundingMode) is an error

let
  x  be a representable finite, nonnegative floating point number
  s₌ be the floating point value of sqrt(x) [RoundNearest]
  s₋ be the floating point value of sqrt(x) [RoundDown]
  s₊ be the floating point value of sqrt(x) [RoundUp]

by definition
```
  s₋ === s₌ || s₋ === prevfloat(s₌)
  s₊ === s₌ || s₊ === nextfloat(s₌)
```

one and only one of these three must hold
```
  (a) s₌ * s₌ === x
      ∴ s₊ === s₋ === s₌
  (b) s₌ * s₌ < x  && s₊ * s₊ > x
      ∴ s₊ === nextfloat(s₌)
  (c) s₌ * s₌ > x  && s₋ * s₋ < x
      ∴ s₋ === prevfloat(s₌)
```

if (a)
  RoundDown: return s₌
  RoundUp  : return s₌

if (b)
  RoundDown: return s₌
  RoundUp  : return nextfloat(s₌)

if (c)
  RoundDown: return prevfloat(s₌)
  RoundUp  : return s₌

```
@inline function sqrt_round(x::T, ::RoundingMode{:Down}) where T<:IEEEFloat
    y = sqrt(x)
    z = y * y
    if z > x
      y = prevfloat(y)
    end
    return y
end

@inline function sqrt_round(x::T, ::RoundingMode{:Up}) where T<:IEEEFloat
    y = sqrt(x)
    z = y * y
    if z < x
      y = nextfloat(y)
    end
    return y
end
```

**Comment by JeffreySarnoff** [comment]
I say it is right.  What say you?

**Comment by JeffreySarnoff** [comment]
@stefan ^

**Comment by JeffreySarnoff** [comment]
@StefanKarpinski put on your floating-point hat, ^

**Comment by JeffreySarnoff** [comment]
Actually it fails for tiny values (3.9036066558023176e-154) .. not sure why, so I have restored the mul_round(y, y, RoundDir) logic.
