### ISSUE TITLE
Bug in mul_round

### ISSUE THREAD

**Issue by dpsanders** [JeffreySarnoff/FastRounding.jl#7]
The following is incorrect:
```jl
julia> mul_round(Inf, Inf, RoundDown)
NaN
```
The result should be `Inf`. 
Note that `mul_round(Inf, Inf, RoundUp)` correctly gives `Inf`.

**Comment by dpsanders** [comment]
I think this is due to https://github.com/JeffreySarnoff/ErrorfreeArithmetic.jl/issues/4

**Comment by JeffreySarnoff** [comment]
fixed
